### ISSUE TITLE
Add package source to PyPI

### ISSUE THREAD

**Issue by sugatoray** [WenjieDu/PyCorruptor#1]
Only `.whl` file is available on PyPI. Please also make available the source (`*.tar.gz`) file.

**Comment by WenjieDu** [comment]
Thank you, @sugatoray 😃 It's on my list!

**Comment by WenjieDu** [comment]
Sorry for the late update. It's already been solved by using [the auto-publishing workflow](https://github.com/WenjieDu/PyCorruptor/blob/main/.github/workflows/publish_to_PyPI.yml), just like PyPOTS and TSDB.
